on: workflow_dispatch
jobs:   
  build_job:
    name: build env test
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v4.0.2
        with: 
          node-version: '20.x'
      - name: install vsce
        shell: pwsh
        run: npm install -g @vscode/vsce
      - name: test vsce
        shell: pwsh
        run: vsce --version
