on: workflow_dispatch
jobs:   
  build_job:
    name: build env test
    runs-on: windows-lastest
    steps:
      - uses: actions/setup-node@v4.0.2
        with: 
          node-version: '20.x'
      - name: test node
        shell: pwsh
        run: node --version
